name: nmtpy

dependencies:
  - python=3.6
  - cffi
  - cython
  - ipython
  - pyyaml
  - protobuf>=0.3.2
  - six
  - typing
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - pillow
  - pip:
    - torch==1.0.0
    - torchvision==0.2.1
    - sacrebleu>=1.2.9
    - tensorboardX==1.1
    - editdistance==0.4
    - subword_nmt==0.3.5
    - ipdb
    - -e .
